name: pet_feed
description: "Mobile app for a good pet-parenting."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.10+1
#   flutter_launcher_icons: "^0.13.1"

# flutter_launcher_icons:
#   android: "launcher_icon"
#   image_path: "assets/img/logo.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/img/
    # - assets/fonts/  
  fonts: 
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
    - family: Aclonica
      fonts: 
        - asset: assets/fonts/Aclonica-Regular.ttf
          weight: 400
    - family:  CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf